### getAll
GET http://localhost:8080/api/category/?sort=id&direction=asc&page=2&size=1

### save category
POST http://localhost:8080/api/category/
content-type: application/json

{
  "name" : "Action",
  "description" : "Hola"
}



### pageable
GET http://localhost:8080/api/movie/?sort=id&direction=asc&page=2&size=1


### findByName
POST http://localhost:8080/api/movie/findByTitle
Content-Type: application/json

{
  "title": "a"
}


### save
POST http://localhost:8080/api/movie/
Content-Type: application/json

{
  "title": "test 2",
  "description": "",
  "director": "{{ $random.alphanumeric(10) }}",
  "category": {
    "id": 1
  }
}

### uodate
PUT http://localhost:8080/api/movie/update/
Content-Type: application/json

{
   "id": 1,
  "title": "{{ $random.alphanumeric(10) }}",
  "description": "",
  "category": {
    "id": 2
  }
}

### disable
PATCH http://localhost:8080/api/movie/change-status/1


