### getAll
GET http://localhost:8080/api/category/?sort=id&direction=asc&page=2&size=1

### save category
POST http://localhost:8080/api/category/
content-type: application/json

{
  "name" : "Segunda",
  "description" : "Hola"
}



### pageable
GET http://localhost:8080/api/movie/


### findByName
POST http://localhost:8080/api/movie/findByTitle
Content-Type: application/json

{
  "title": "Alejan"
}

### findByDirectorName
POST http://localhost:8080/api/movie/findByDirectorName
Content-Type: application/json

{
  "director": "li"
}

### findByBeetwenDates
POST http://localhost:8080/api/movie/findBetweenDates
Content-Type: application/json

{
  "atPublishStart": "2000-02-18",
  "atPublishEnd": "2024-02-20"
}

### findByCategory
POST http://localhost:8080/api/movie/findByCategory
Content-Type: application/json

{
  "category": {
    "id": 2
  }
}


### findByDate
POST http://localhost:8080/api/movie/findByDate
Content-Type: application/json

{
  "atPublish": "2024-05-19"
}




### save
POST http://localhost:8080/api/movie/
Content-Type: application/json

{
  "title": "{{ $random.alphanumeric(15) }}",
  "description": "",
  "director": "{{ $random.alphanumeric(10) }}",
  "category": {
    "id": 2
  }
}

### uodate
PUT http://localhost:8080/api/movie/update/
Content-Type: application/json

{
   "id": 1,
  "title": "{{ $random.alphanumeric(10) }}",
  "description": "",
  "category": {
    "id": 2
  }
}

### disable
PATCH http://localhost:8080/api/movie/change-status/1


